version: "3.8"

services:
  # test-db:
  #   image: postgres:16.1
  #   container_name: test-db
  #   env_file:
  #     - .env
  #   environment:
  #     POSTGRES_USER: ${TEST_DB_USER}
  #     POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
  #     POSTGRES_DB: ${TEST_DB_NAME}
  #   ports:
  #     - ${TEST_DB_PORT}:5432
  #   networks:
  #     - backend

  postgres-db:
    image: postgres:16.1
    container_name: postgres-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    networks:
      - backend
  backend:
    container_name: diploma-backend
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres-db
      # - test-db
    environment:
      - DB_HOST=postgres-db
    # entrypoint: ["/docker/app.sh"]
    networks:
      - backend

networks:
  backend:
    driver: bridge
