"""alter pk column name -> id

Revision ID: e2b74cc89a85
Revises: 4f15a34a11bd
Create Date: 2024-03-01 22:24:49.112463

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e2b74cc89a85"
down_revision: Union[str, None] = "4f15a34a11bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("refresh_token", "rt_id", new_column_name="id")
    op.drop_index("ix_refresh_token_rt_id", table_name="refresh_token")
    op.create_index(op.f("ix_refresh_token_id"), "refresh_token", ["id"], unique=False)

    op.alter_column("user", "user_id", new_column_name="id")
    op.drop_index("ix_user_user_id", table_name="user")
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "id", new_column_name="user_id")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.create_index("ix_user_user_id", "user", ["user_id"], unique=False)
    op.alter_column("refresh_token", "id", new_column_name="rt_id")

    op.drop_index(op.f("ix_refresh_token_id"), table_name="refresh_token")
    op.create_index("ix_refresh_token_rt_id", "refresh_token", ["rt_id"], unique=False)
    # ### end Alembic commands ###
