name: Lint and check types

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install poetry
        run: |
          pip install pipx
          pipx install poetry

      - name: Validate the structure of the pyproject.toml
        run: |
          poetry check

      - name: Verify that poetry.lock is consistent with pyproject.toml
        run: |
          poetry lock --check

      - name: Install dependencies
        run: |
          poetry install
#
#      - name: Check tests
#        run: |
#          poetry run pytest
